CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE 
IF NOT EXISTS businesses(
  uuid uuid UNIQUE DEFAULT uuid_generate_v4(),
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  ADDRESS_LINE1 VARCHAR(255),
  ADDRESS_LINE2 VARCHAR(255),
  SUBURB VARCHAR(255),
  STATE VARCHAR(255),
  COUNTRY VARCHAR(255),
  POSTCODE VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updatedAt TIMESTAMP DEFAULT NULL
);

CREATE RULE businesses_update AS ON UPDATE TO businesses  
    WHERE   NEW<>OLD
    DO UPDATE businesses SET updatedAt=CURRENT_TIMESTAMP
